import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/ui/components/nav-bar";

const excelsior = localFont({
  src: [
    {
      path: "./fonts/Excelsior.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Excelsior_Italic.woff2",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-excelsior",
});

// const dkOtago = localFont({
//   src: "./public/fonts/DK_Otago.woff2",
//   variable: "--font-dk-otago",
//   weight: "400",
//   style: "normal",
// });


export const metadata: Metadata = {
  title: "Sherpa Food Tours",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${excelsior.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
